title: Steve Teuber - DevOps Engineer
params:
  meta:
    keywords:
    - Automation
    - AWS
    - CI/CD
    - Cloud Native
    - DevOps
    - Docker
    - GitHub
    - Go
    - Grafana
    - Infrastructure as Code
    - Kubernetes
    - Observability
    - Open Source
    - Podman
    - Pulumi
    - Security
    - Terraform
    description: >-
      Hi! I'm Steve. I'm a DevOps Engineer with a focus on Automation and Security.
      My daily toolset includes AWS, GitHub, Go, Grafana, Kubernetes, Podman and Pulumi.
      However, I'm trying to find things that are really cool and not just a hype.
  avatar:
    url: https://avatars.githubusercontent.com/steveteuber
    name: Steve Teuber
    title: DevOps Engineer
    intro: >-
      Hi! I'm Steve. I'm a DevOps Engineer with a focus on **Automation** and **Security**.
  social:
  - icon: github
    url: https://github.com/steveteuber
  - icon: docker
    url: https://hub.docker.com/u/steveteuber
  - icon: linkedin
    url: https://linkedin.com/in/steve-teuber
  - icon: xing
    url: https://xing.to/steveteuber

disableKinds: [rss, sitemap, taxonomy, term]

module:
  imports:
  - path: github.com/FortAwesome/Font-Awesome
    mounts:
    - source: svgs/brands
      target: assets/svgs
    - source: svgs/solid/terminal.svg
      target: assets/favicon.svg
